name: 🐍 GitHub Snake Contribution Animation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches: [main, master]

env:
  GITHUB_USER: rbanik1204

jobs:
  generate-snake:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate Basic Snake
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ env.GITHUB_USER }}
          outputs: output/github-contribution-grid-snake.svg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Dark Theme Snake
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ env.GITHUB_USER }}
          outputs: output/github-contribution-grid-snake-dark.svg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: List Generated Files
        run: |
          echo "Generated snake files:"
          ls -la output/
          echo "File sizes:"
          du -h output/*

      - name: Commit and Push Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add output/
          git commit -m "🐍 Update snake animations [skip ci]" || echo "No changes to commit"
          git push
