name: 🐍 Generate Snake Contributions

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches: [main, master]

env:
  GITHUB_USER: rbanik1204

jobs:
  generate-snake:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate Basic Snake
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ env.GITHUB_USER }}
          outputs: dist/github-snake.svg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Dark Theme Snake
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ env.GITHUB_USER }}
          outputs: dist/github-contribution-grid-snake-dark.svg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: List Generated Files
        run: |
          echo "Generated snake files:"
          ls -la dist/
          echo "File sizes:"
          du -h dist/*

      - name: Commit and Push Changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add dist/
          git diff --staged --quiet || git commit -m "🐍 Update snake animations [skip ci]"
          git push
